export const WRITE_REVIEW_REQUEST = "WRITE_REVIEW_REQUEST";
export const WRITE_REVIEW_SUCCESS = "WRITE_REVIEW_SUCCESS";
export const WRITE_REVIEW_FAIL = "WRITE_REVIEW_FAIL";
export const WRITE_REVIEW_RESET = "WRITE_REVIEW_RESET";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const ADMIN_REVIEWS_REQUEST = "ADMIN_REVIEWS_REQUEST";
export const ADMIN_REVIEWS_SUCCESS = "ADMIN_REVIEWS_SUCCESS";
export const ADMIN_REVIEWS_FAIL = "ADMIN_REVIEWS_FAIL";
